version: "3.8"

services:
  db:
    image: mysql:8
    container_name: stacktodo-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stacktodo
      MYSQL_USER: stackuser
      MYSQL_PASSWORD: 1234!
      MYSQL_ROOT_PASSWORD: 1234!
      TZ: Asia/Seoul
    ports:
      - "3306:3306"   # 로컬에서 localhost:3306

volumes:
  dbdata: